### ISSUE TITLE
The output directory is always C:\ with -m

### ISSUE THREAD

**Issue by Luct0r** [SnaffCon/Snaffler#128]
Hey there, amazing tool - really great work!

One thing that has confused me is when I use `-m` and provide a directory it always seems to put interesting files in `C:\` instead?

Not a big deal and I'm probably doing something wrong but curious nonetheless.

Thanks

**Comment by l0ss** [comment]
Hey i finally got around to testing this and I can't reproduce it. Is this still happening?

**Comment by checkymander** [comment]
I can second this I'm getting the same result with the following command and a fresh snaffler:

```
Snaffler.exe -i \\<ip>\Shared -o snafflog.log -m C:\users\checkymander\Desktop\SnafflerOut\
```

and I get a new folder in `C:\`
![image](https://github.com/SnaffCon/Snaffler/assets/26147220/9d9ed15f-4c50-4b5f-8419-015d254d5ad1)

**Comment by jeffmcjunkin** [comment]
I had the same experience today. Invocation was: `Snaffler.exe -s -o snaffler-log.txt -m  -x 12`, and the output folders (one per destination computer) were made at the root of the C drive.

**Comment by omnifocal** [comment]
+1 This has always been the case for me and I've never known why

**Comment by 7MinSec** [comment]
Adding a "me too!" here.  I did `snaffler.exe -s -o snaffy.log -m dump` thinking stuff would dump in my `dump` folder, but it's all going to C:\

**Comment by MacGovery** [comment]
Adding a "me too!" here. I did `C:\temp\Snaffler\Snaffler.exe -s -o C:\temp\Snaffler\snaffler.log -v trace -i \\host\share -p C:\temp\Snaffler\SnaffRules -m C:\temp\Snaffler\Found`

**Comment by mplattner** [comment]
Same for me. Using `.\snaffler.exe -s -m ".\files\" -o sna-withfiles.log` while being in a subdirectory of `C:/myfolder/`. A separate directory for each machine is created under `C:/`.

**Comment by 7MinSec** [comment]
Thank you!

**Comment by mplattner** [comment]
Great news, thanks! 👍

**Comment by jeffmcjunkin** [comment]
Woot!
