### ISSUE TITLE
Feature Suggestion: Easy way to scan client PCs only

### ISSUE THREAD

**Issue by mschomm** [SnaffCon/Snaffler#134]
Got Snaffler recommended recently and love it so far. Now I'd like to do a daytime scan of client PCs only. AFAIK currently the only way to scan individual hosts is to use `-n` and specify them individually. Fine so far and I guess I can squeeze all the client names to scan into the 8191 max char limit of a command prompt line. But there might be more comfortable options, e.g.:
- Specify a file containing one host name per line
- Specify one or more OUs to use for computer account enumeration
- Specify a name pattern for the computer accounts to be included in the scan

Edit: I just found out via `-z generate` that it is possible to use an individual `ComputerTargetsLdapFilter` if you specify an options file. Will try this, looks like a good way to achieve some of what I have in mind.

**Comment by l0ss** [comment]
sounds like it's under control - reopen if you decide it isn't working.
