### ISSUE TITLE
Support for CSV export

### ISSUE THREAD

**Issue by sanitycheck** [SnaffCon/Snaffler#137]
Hi @l0ss  and @Sh3r4 ,

First off, thank you for creating such a fantastic tool! I've used it on multiple assessments now, and it has consistently found troves of credentials, secrets, or other sensitive bits of information that would have otherwise led to a significant compromise.

I wanted to ask if you have any plans to support CSV exports from Snaffler? If not, is there a strongly typed JSON schema available so that JSON output can be reliably parsed and processed?

**Comment by l0ss** [comment]
i'm pretty sure if you do `-y ","` that will do CSV output. `-y` defaults to TSV but you should be able to specify the separator of your choice.

**Comment by nbandodk** [comment]
Hi! I tried using the `-y ","` trick but it didn't work for me. Is the "Separator" field in the toml config file useful for this?
