### ISSUE TITLE
Is writing exception messages to the output file expected behavior for "-v data"?

### ISSUE THREAD

**Issue by lynnewu** [SnaffCon/Snaffler#138]
For instance, when an exception is thrown at C:\src-ssb\Snaffler\SnaffCore\Classifiers\FileClassifier.cs:line 268, the handler uses Mq.error() to write the exception information to the output file.

Unfortunately, if you're trying to write out a TSV file, this makes the output file unparseable because the output gets written to multiple lines. 

I'm specifying "-v data", which I thought would suppress errors of this sort.

**Comment by l0ss** [comment]
While I had originally assumed the user would always want to see errors, I can see how automated parsing might be a situation where you want them suppressed. I'll try to find some time to fix this up.
