### ISSUE TITLE
Snaffler ignores exclusions

### ISSUE THREAD

**Issue by MacGovery** [SnaffCon/Snaffler#141]
So i wanted to exclude some Hosts with:

` -k, --exclusions[optional]... Path to a file containing a list of computers to exclude from scanning.`

I tried:
` .\Snaffler.exe -z .\default.toml -k .\SnaffRules\exclusions.txt`

In the exclusions.txt i tried it directly with a `IP Address` and `Hostname `and `Hostname.Domain.FQDN` each one separately.

The excluded Host was still beeing ujsed in the scan. 

```
...
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Parsing args...
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Read config file from .\default.toml
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Parsed args successfully.
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Invoking DFS Discovery because no ComputerTargets or PathTargets were specified
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Getting DFS paths from AD.
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Found 421 DFS Shares in 496 namespaces.
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Invoking full domain computer discovery.
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Getting computers from AD.
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Got X computers from AD.
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Info] Starting to look for readable shares...
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Share] {Green}<\\excludedserver.domain.com\share>(R)
[DOMAIN\user@server] 2024-03-07 05:21:01Z [Share] {Green}<\\excludedserver2.domain.com\share2>(R)
..
```

What I'am missing?

**Comment by l0ss** [comment]
Use of a config file with -z will override any/all other arguments you provide.

If you try running `Snaffler.exe -k .\SnaffRules\exclusions.txt -z generate` (back up your default.toml first) it will generate you an example config file with the exclusion folder setting in it. You can then add that to your existing config file going forwards.

**Comment by MacGovery** [comment]
If I use:
.\Snaffler.exe -k .\SnaffRules\exclusions.txt -p .\SnaffRules -z generate
how do i force the usage of the generated default.toml?
How can I verify, that the excluded hosts are not touched?

If I run:
`.\Snaffler.exe  --config .\default.toml`
I get:
```
System.ArgumentException: Pointless argument combination.
   at Snaffler.Config.ParseImpl(String[] args)
   at Snaffler.Config.Parse(String[] args)
   at Snaffler.SnaffleRunner.Run(String[] args)
Parsing args...
Enabled logging to stdout.
Read config file from .\default.toml

You didn't enable output to file or to the console so you won't see any results or debugs or anything. Your l0ss.
System.ArgumentException: Pointless argument combination.
   at Snaffler.Config.ParseImpl(String[] args)
Something went wrong parsing args.
I snaffled 'til the snafflin was done.
```
