### ISSUE TITLE
Snaffler Stop the Scanning after 5 min

### ISSUE THREAD

**Issue by HRT040** [SnaffCon/Snaffler#143]
After 5 Min stop the Scanning:

i Used -i network folder path and -o Log path folder:

2024-06-18 07:48:57Z [Info] Snafflin' took 00:05:00.0121477
Snaffler out.

2024-06-17 14:27:06Z [Info] Snafflin' took 00:05:00.0121481
Snaffler out.

 2024-06-17 14:42:40Z [Info] Snafflin' took 00:05:00.0121678
Snaffler out.

i tried with another User, with -v debug and another .toml config File. it will stop the scanning after 5 Mins. do anyone have any idea? :)

**Comment by hasksomatotoian** [comment]
There is an undocumented command line parameter `-e` which has description _"Interval between status updates (in minutes) also acts as a timeout for AD data to be gathered via LDAP. Turn this knob up if you aren't getting any computers from AD when you run Snaffler through a proxy or other slow link. Default = 5"_ (see [line 108 in Config.cs](https://github.com/SnaffCon/Snaffler/blob/ae01ab974b543cd167db649a1c359b00d413905c/Snaffler/Config.cs#L108C17-L108C255)) .
Append parameter like `-e 10` to your command.

**Comment by l0ss** [comment]
If you're using -i to specify a path then the -e arg won't help you much as that's only useful when there's too many computers in AD and it times out while doing the initial ldap queries.

Try running with -v trace and see if that tells you anything informative. My guess is that for whatever reason Snaffler can't even read/list the path you're providing, but I would need more details to figure out why. Are you possibly using a trailing slash on the path?

**Comment by l0ss** [comment]
closing this pending further information.
