### ISSUE TITLE
Enumerate specific remote host local path

### ISSUE THREAD

**Issue by fatmeat** [SnaffCon/Snaffler#156]
Does it possible to scan a remote host and it's local path?
Like Snaffler.exe --RemoteTarget 192.168.0.1 --RemoteTargetPathToBeScan C:\

**Comment by checkymander** [comment]
the `-i` flag lets you specify a specific UNC path e.g. `\\192.168.0.1\C$\`

**Comment by fatmeat** [comment]
> the `-i` flag lets you specify a specific UNC path e.g. `\\192.168.0.1\C$\`
> 
> Edit: Sorry misread, you'll be able to enumerate local path's e.g. C:\ if you're an admin on the box, and set the share to C$ for C: D$ for D:\ etc etc

Thank you for the prompt reply, I can enumerate success remotely.

One more follow up question, what about a list of remote target's local path?
Snaffler.exe -s -i \\TARGETLIST\C$

**Comment by l0ss** [comment]
that's a good idea, and shouldn't be too hard to add - but i haven't had much time for dev lately. If someone submits a PR for it I'd be on board.
