### ISSUE TITLE
High rate of false positives with the new KeepPassOrKeyInCode.toml

### ISSUE THREAD

**Issue by 7Wires** [SnaffCon/Snaffler#158]
The 15th of October the rule "Snaffler/SnaffRules/DefaultRules/FileRules/Keep/Code/KeepPassOrKeyInCode.toml" has been modified including also this row:
"-passw?o?r?d?"

In my opinion this generates a lot of false positives (at least in my context), I would suggest to modify this rule so that only rows that start with "-passw?o?r?d?" or have at least a space before "-passw?o?r?d?" are matched. I expect that a password parameter is at the beginning of the row or somewhere as a parameter. Otherwise any string "something-pass" matches. E.g. "city-passage" just to give you an example of the thousands of false positives I have.

E.g. the row might be substituted by these new two rows (probably there is also a way to use only a single regex):
"^-passw?o?r?d?"
"[\s]+-passw?o?r?d?"

**Comment by l0ss** [comment]
requiring a leading space seems like a good idea - implemented in #159
