### ISSUE TITLE
Feature Request - HTML report

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [SnaffCon/Snaffler#17]
I took a quick look at the code to see if for example a HTML report can be generated as output instead of the log with text only. Seams that the output is not generated at a single point in the code but from different modules at run time am i right?

Im missing some output format like html here were the links can be clicked and the colours still remain. This would really improve the usability when running the tool in the background.

Greetings

**Comment by l0ss** [comment]
If you have a look at how i've added the TSV output option in the most recent merge from tribunal branch, it should be reasonably straightforward to add an output option that bolts some link and colour tags around each element in a line of output. I'll add it to the TODO.

**Comment by Sh3r4** [comment]
Between this and the TSV request, I'm thinking we will get more output type requests. We should maybe move the output logic into an OOP-ish approach. I'll add some architecture notes to the todo :)

**Comment by S3cur3Th1sSh1t** [comment]
I really like the [dionach passhunt.py](https://raw.githubusercontent.com/Dionach/PassHunt/master/passhunt.py) report, maybe something like this could also be used here.  There is an html table entry for each Share-Name and the regex output. Maybe its possible to store the share-paths and regex output in an array and generate the report at the end by using the array values. 

But than the report is only generated when snaffler exits successfully. I also had situations when it ran ~24h in an environment making the client unstable because of the CPU/Memory usage, so this would not generate an report.


    css = """<style type="text/css">
                    table {border-collapse:collapse;}
                    table, td, th {border:1px solid darkgray;}
                    td {padding-left:5px; padding-right:5px;}
                    .t1 {font-weight: bold;}
                    .s1 {background-color: lightblue;}
                    .s2 {background-color: yellow;}
                    .s3 {background-color: orangered;}
                    .ts {font-weight: normal; font-size: smaller}
                    </style>"""

    report = u'<html><head><title>Pass Hunt Report</title>%s</head><body>\n' % (css)
    report += u'<h1>Pass Hunt Report - %s</h1>\n' % (time.strftime("%H:%M:%S %d/%m/%Y"))
    report += u'<p>Searched %s\nExcluded %s</p>\n' % (search_dir, excluded_directories_string)
    report += u'<p>Command: %s</p>\n' % (' '.join(sys.argv))
    report += u'<p>Uname: %s</p>\n' % (' | '.join(platform.uname()))
    report += u'<p>Searched %s files. Found %s possible passwords.</p>\n' % (total_docs, pwds_found)
    
    report += u'<table>'
    for afile in sorted([afile for afile in all_files if afile.matches]):
        report += '<tr><td class="t1 s1"><a href="file://%s">%s</a> (%s %s)</td></tr>\n' % (afile.path, afile.path, afile.size_friendly(), afile.modified.strftime('%d/%m/%Y'))
        pwd_list = u'' + u'<br />'.join([u'<b>{0}</b> {1}'.format(pwd.sub_path, esc_xml(pwd.pwd)) for pwd in afile.matches])
        report += '<tr><td>%s</td></tr>\n' % pwd_list
    
    if len([afile for afile in all_files if afile.type == 'OTHER']) <> 0:
        report += u'<tr><td class="t1 s1">Interesting Files to check separately:</td></tr>\n'
    for afile in sorted([afile for afile in all_files if afile.type == 'OTHER']):
        report += u'<tr><td><a href="file://%s">%s</a> (%s %s)</td></tr>\n' % (afile.path, afile.path, afile.size_friendly(), afile.modified.strftime('%d/%m/%Y'))

    report += u'</table></body></html>'
`

**Comment by l0ss** [comment]
given the memory headaches trying to do something like this in large environments, is there actually any advantage to generating variant output formats within snaffler itself rather than just doing stuff to the tsv output elsewhere?

**Comment by Sh3r4** [comment]
yeah, @l0ss that's a very good point. There is an architectural reason to purge results from memory as soon as they are reported to the output logic. We can probably close this feature request as not won't do. Our main output is greppable, we have a TSV option and sed exists. Did I miss anything?

**Comment by S3cur3Th1sSh1t** [comment]
You are right TSV most likely covers all use cases here. I‘ll stick around with that in the next weeks and close this issue.
