### ISSUE TITLE
Running snaffler with custom toml file and parameters

### ISSUE THREAD

**Issue by ville87** [SnaffCon/Snaffler#27]
Hello there, 

first of all: thanks for your work on this great tool! :)

I'm in a scenario where I'd like to add some custom search patterns via a toml file, but only search in a custom path.
I realized that once you define a toml file with the -z, all other parameters seem to be ignored. (I wanted to add "-i D:\somefolder\path")

Is this by design, that it ignores other parameters? If yes, how can I define a custom search path in the toml file?

Thanks,
Ville

**Comment by l0ss** [comment]
if you do `snaffler.exe -s -o snaffler.log -i D:\somefolder\somepath -z generate` the generated toml file will include the appropriate settings from the command line args. This should let you see how they work. Alternatively there's a sample .toml in the root of the repo that has examples of targeting specific shares etc. Let me know how you go.

**Comment by ville87** [comment]
worked perfectly, thank you!
