### ISSUE TITLE
Parsing logs

### ISSUE THREAD

**Issue by hkelley** [SnaffCon/Snaffler#29]
Has anybody written a log parser?   Adversarial/red users can possibly get by with a visual scan of the Snaffler log to get what they need.   Defenders, especial in environments with hundreds of servers,  need to be able to get the Snaffler log into analysis tools to properly review all of the data.

I've started working on parsing in Powershell but I'd appreciate a pointer if anybody has already covered this ground.

```
param
(    
    [Parameter(Mandatory = $true)] [string] $SnafflerLog
)

$fileItem = Get-Item $SnafflerLog

$reader = New-Object -TypeName System.IO.StreamReader -ArgumentList $fileItem

$pattern = '(?smi)(?<date>.*?) \[(?<type>.+?)\]\s+\{(?<level>.+?)\}\<*(?<rule>.*?)\>*\((?<path>\\\\.+?)\)(?<matched_string>.*)'
$lineRegex = [regex] $pattern

$lineNum = 0

while ($line = $reader.ReadLine() ) 
{   
    $lineNum++ 

    if ($line -match $lineRegex ) 
    {
        # Rules can have unescaped pipes in the regexes so we can't pluck those out (easily) with other regexes
        #   <KeepConfigRegexRed|R|CREATE (USER|LOGIN) .{0,200} (IDENTIFIED BY|WITH PASSWORD)|4.2kB|27/02/2014 13:44:25>
        # Therefore,  we have to nibble our data from both ends of the split array and treat all elemnts that remain in the middle as the pattern match

        $ruleParts = $Matches.rule.Trim() -split '\|'
        $endOfMatchedRegex = $ruleParts.count-3
        $matched_rule = $ruleParts[0]
        $access_level = $ruleParts[1]
        $matched_regex = ($ruleParts[2..$endOfMatchedRegex] -join "|")
        $last_modified = $ruleParts[-1]

        $path = $Matches.path.Trim()
        $type = $Matches.type.Trim()

        $path_parts = $path -split '\\'
        $server =  $path_parts[2]
        $share =   $path_parts[3]
        if($type -eq "file")
        {
            $extension =  ($path_parts[-1] -split "\.")[-1]
        }
        else
        {
            $extension = $null
        }
        
        [pscustomobject] @{
            level = $Matches.level.Trim()
            type = $Matches.type.Trim()
            path = $path
            server = $server
            share = $share
            extension = $extension
            matched_rule = $matched_rule
            access_level = $access_level
            matched_regex = $matched_regex
            last_modified = $last_modified
            matched_string = $Matches.matched_string.Trim()
            log_line_num = $lineNum
        }            
    }
    else
    {
        
#       Handle mutli-line records
    }
}
```

**Comment by l0ss** [comment]
I’m not aware of anyone else working on this problem but I’m happy to make some minor changes to the output format to facilitate it.

**Comment by hkelley** [comment]
I think a JSON output would work well for most consumers.

**Comment by hkelley** [comment]
It would be helpful to have consistent date formatting too:

`2021-02-28 20:00:33 -05:00 [File]  {Red}<KeepConfigRegexRed|RW|connectionstring[[:space:]]*=[[:space:]]*[\'\"][^\'\"].....*|1.3kB|30/06/2017 09:48:33> . . .
`

ISO format is used for the first date but a localized date is used in the file data.  This gets tricky when doing cross-cultural snaffling.

I'll see if a pull request for this is within my means.

**Comment by hkelley** [comment]
While I was in the code looking at issue #31 I realized there is a TSV format and Options.Separator.   That ought to make log ingestion much simpler.

I have also modified the code to use .NET's "Universal" time format and UTC for file logs.   Will figure out how to do a PR for this.

**Comment by l0ss** [comment]
sounds good to me. I'm gonna assume that means you're happy for me to close this.
