### ISSUE TITLE
README examples show [[Classifiers]] stanzas - sample file shows [[ClassifierRules]]

### ISSUE THREAD

**Issue by hkelley** [SnaffCon/Snaffler#30]
It looks like "[[ClassifierRules]]" is the stanza to use now.   Should the README be updated or does "[[Classifiers]]" do something different?

**Comment by l0ss** [comment]
Yeah you're right. We went back and forth on what they were called a whole bunch during dev. We fell afoul of the second hard thing in computer science: naming things. I'll slap fixing it on the TODO list, but the example config file (and those generated by `-z generate` should work fine still.
