### ISSUE TITLE
BytesToString() for TSV output?

### ISSUE THREAD

**Issue by hkelley** [SnaffCon/Snaffler#34]
This is probably a matter of personal taste,  but I think that the TSV output should skip the BytesToString() translation.    I assume that anyone who wants TSV output will be either consuming output with another tool or going straight to Excel.     In those cases,  it would be more useful to have raw digits.

Before I start a PR for this,  are there reasons to keep the human-friendly format in the TSV output?    

There is  also a spare delimiter that needs to be removed at the beginning of the TSV template:

```
fileResultTemplate = Options.Separator + "{0}" + Options.Separator + "{1}"  . . . .
```

This results in a double-up here (between File and Red):

```
#[File]##Red#KeepConfigRegexRed#
```

I'll fix that in the same PR if the TSV item above is agreeable.

**Comment by l0ss** [comment]
Sorry for taking so long to get back to you - real life is like that.

I'm on board with the changes you describe, feel free to put together a PR and we'll take a squiz.
