### ISSUE TITLE
Way to specify list of targets?

### ISSUE THREAD

**Issue by infosecconsultant** [SnaffCon/Snaffler#35]
Hi. Thanks for the tool! 
Is there a way to provider snaffler a list of targets or a range (like 10.0.0.0/24) to look through? 
I'm currently looping through -i with a script. But that feels kinda dirty. 
Thanks!

**Comment by l0ss** [comment]
if you add `-z generate` to your command line that will produce a config file with the rest of your cmdline options incorporated into it.
Add:
`ComputerTargets = ["computer1", "computer2"]`
or
`PathTargets = ["Z:\\temp","C:\\thing"]`
to the config file and run again with `-z configfile.toml`

Cheers!
