### ISSUE TITLE
Feature Request: Snaffler rga integration for office docs and PDFs

### ISSUE THREAD

**Issue by cmprmsd** [SnaffCon/Snaffler#36]
Hey there, 

Awesome tool you created there! 

Pasting of Office docs and pdfs seems to be a whole new topic on itself and I wonder if you would find it interesting to integrate ripgrepall (rga) into Snaffler. 
The tool parses many filetypes for their content. It is written in rust, but still might be worth a shot as I see the plan in your to-do list 😁

**Comment by l0ss** [comment]
Bad news, we're not integrating rga. Good news, we don't need to cos we have UltraSnaffler on the way, which can look inside office docs and pdfs. Check out the DevCrimes branch for a preview.

**Comment by cmprmsd** [comment]
Awesome. Looking forward to the release!

**Comment by l0ss** [comment]
oh btw i just renamed that branch to UltraSnaffler, in case you can't find it :D

**Comment by cmprmsd** [comment]
Yup already found it :D 
Uhm, there is a fork of the master branch that adds some German word regex combinations from Jonas. Feel free to add it to UltraSnaffler 😆 It was created out of a discussion at work :)

**Comment by cmprmsd** [comment]
Hi! Long time no see :laughing: 

A huge lack of time (daughter :D) caused some delay in testing the word, excel feature. 

It seems Ultrasnaffler does not find delicious content in Word or Excel files even when I guide it to find some.

`PathTargets = ["C:\\\\Users\\\\user\\\\Desktop\\\\Dev\\\\Snaffler\\\\scanme"]`

![image](https://user-images.githubusercontent.com/73472903/129550441-70ab0ad7-dadb-4ab2-b967-502f1776e146.png)

Am I missing a special flag for scanning content the --ultra way? :smiley:
