### ISSUE TITLE
Compilation of Ultrasnaffler does not work

### ISSUE THREAD

**Issue by cmprmsd** [SnaffCon/Snaffler#56]
Hey Mike,

I'm having some trouble compiling the code for UltraSnaffler.

I get an error for missing assembly references on:
```csharp
using SnaffCore.Classifiers
```

There is also "Snaffcore.dll not found."

This is what I get when I run "create project" or "projectmappe" how it's called in German VS :rofl: 

Snaffler builds fine with the Snaffler solution file, but I cannot get it built with UltraSnaffler.sln

**Comment by l0ss** [comment]
That sounds like you’re trying to build the individual project rather than the whole solution?

**Comment by cmprmsd** [comment]
I'm trying to compile the full solution :(

**Comment by l0ss** [comment]
If you can post the english language error that would help a lot, thanks!

**Comment by cmprmsd** [comment]
Sure thing! :) 

![image](https://user-images.githubusercontent.com/73472903/130194349-a614baf8-76ec-4580-8f16-faa0861adbed.png)
![image](https://user-images.githubusercontent.com/73472903/130194432-2835efd1-f2f6-444c-9937-02c3930db5b4.png)

**Comment by cmprmsd** [comment]
In the end, the warning messages could be ignored, as they tell me "hey I picked one version for you", right?
So the namespace problem seems to be my spoilage.

**Comment by cmprmsd** [comment]
I'm messing around and now get another error message, which hints, that SnaffCore.dll is not referenced correctly. 
![image](https://user-images.githubusercontent.com/73472903/130684162-ea25af34-3c92-4df3-9ab8-33b5a818782f.png)

I tried referencing it manually but this does not result in a proper build with doc or docx parsing :cry:

**Comment by cmprmsd** [comment]
@l0ss Everything alright? 😟

**Comment by l0ss** [comment]
yeah sorry man I have been busy with a new job and trying to make progress on group3r.

taking a look now.

**Comment by l0ss** [comment]
check out https://github.com/SnaffCon/Snaffler/tree/fix-for-56 and please let me know if it works for you.

**Comment by cmprmsd** [comment]
Congrats dude! 

I compiled it and the build now says no errors 👍 
However, I started the scanner with the parameter `-i c: \\abc\\ -s` with some xls and xlsx files and the string password in it. (had to Google for some :D). It did not detect the string in the documents. 

Do I need to have Office on the computer that machine? 

The release binary is 5660KB sized (for comparison). 

Is there a way to recognize that UltraSnaffler is running? (different banner or parameters in the help menu).

**Comment by l0ss** [comment]
you have to write your own .doc and .xls rules for ultrasnaffler - there aren't any defaults.

No you don't need office, that's why the release binary is so big - it could be a lot smaller if i didn't have to jam a massive office doc parser into it.

I'll add an item to the TODO list to make the banner different - someone else was asking for a version number so i'll do both at the same time.

**Comment by cmprmsd** [comment]
Thanks! I'll have a look building some 😊
