### ISSUE TITLE
Output Files are not UTF-8 encoded

### ISSUE THREAD

**Issue by cmprmsd** [SnaffCon/Snaffler#58]
Currently the log-files that Snaffler outputs are ANSI encoded. However, at least VSCode opens the file with UTF-8 encoding and misses e.g. German umlauts:

![image](https://user-images.githubusercontent.com/73472903/130799974-d22deeac-1f6e-4984-989e-a73fb8a8d183.png)

Currently I work around this issue by clicking on UTF-8 and "Reopen the document" with `Western (ISO 8859-1)` encoding in order to see the umlauts correctly. 

I guess this issue is even more visible for other languages :sweat_smile: 

Btw: Rainbow CSV for VSCode is awesome to view the tool output!

**Comment by l0ss** [comment]
is this a snaffler problem or just an issue with how vscode opens files by default?

**Comment by cmprmsd** [comment]
Sorry, I also got busy. Vscode looks at the meta data of the file and I would guess that the file write action has to contain the encoding. Default might be ISO.
