### ISSUE TITLE
Snaffler lists files as interesting even though they cannot be read by the current user

### ISSUE THREAD

**Issue by ss23** [SnaffCon/Snaffler#62]
Snaffler keeps telling me about all the juicy things it has found, but while I have permission to see they exist, I can't actually read the file it wants to snaffle.

It would be good to be able to filter these out (ideally by default).

**Comment by l0ss** [comment]
This is definitely a problem  and it's going to the top of the TODO list.

**Comment by hkelley** [comment]
Similar (or perhaps polar opposite) to #64.

Could we use the gray triage level for these access denied files too?

**Comment by l0ss** [comment]
fixed in #69
