### ISSUE TITLE
Specify credentials to use

### ISSUE THREAD

**Issue by infosecconsultant** [SnaffCon/Snaffler#63]
Hello.
Another feature request that I think would be handy. 
I'd like to be able to run snaffler from a non-domain joined machine by specifying:

`-u username -p password -d domain`

Doing this allows me to easily test different users in different groups and review different sets of permissions by simply comparing the output without having to mess around with runas or proxying through something else.

Would be a very handy feature to have. 

Thanks

**Comment by l0ss** [comment]
it's definitely a nice idea and it's on the roadmap, but it's not suuuuper simple to implement.

in the meantime you can use runas /netonly on non-domain-joined machines.
