### ISSUE TITLE
Load as assembly (System.Reflection.Assembly) and Environment.Exit

### ISSUE THREAD

**Issue by PfiatDe** [SnaffCon/Snaffler#66]
When loading the .exe reflective in a Powershell Session, e.g. like this:
` 
$a = [Convert]::ToBase64String([IO.File]::ReadAllBytes("C:\tools\Snaffler\Snaffler\bin\Release\snaffler.exe"))
$Snaffler = [System.Reflection.Assembly]::Load([Convert]::FromBase64String($a))
[Snaffler.Snaffler]::Main("-h")
`
(Yes the base64 encode / decode is useless in this case, but needed in the final script)
the Environment.Exit statements are exiting the complete hosting powershell process. Any idea to prevent this? Commenting the statements seem to avoid that problem, but of course then the threads do not exit properly and the memory usage is extreme, until a crash occours.

**Comment by l0ss** [comment]
oh hey i have fixed this now. wheeeeee!
