### ISSUE TITLE
Any examples of cascading relays ?

### ISSUE THREAD

**Issue by hkelley** [SnaffCon/Snaffler#67]
I'm trying to finesse the connection string rules so that those with Integrated Auth are triaged at Yellow and all others (presuming they will have SQL passwords) are Red.

I tried the following (multiple rules, same name,  hoping the relay might call each).  No dice.  Only one rule seems to survive.

Any other tricks?

```
# Need this relay to hook the next rule
[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "ConfigContentByExt"
MatchAction = "Relay"
RelayTarget = "KeepConfigRegexXXXX"
Description = "Files with these extensions will be subjected to a generic search for keys and such."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = [ ".json", ".config"]
Triage = "Green"

[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepConfigRegexXXXX"
MatchAction = "Snaffle"
Description = "Match SQL connection strings that appear to have a password."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = ["Data Source=.+Password=.+"]
Triage = "Red"

[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepConfigRegexXXXX"
MatchAction = "Snaffle"
Description = "Match SQL connection strings that appear to use integrated security (so no passwords)."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = ["Data Source=.+Integrated Security=true"]
Triage = "Yellow"

```

**Comment by l0ss** [comment]
OK so I remembered right - FileScanner.cs line 130 uses a .First() to choose the relay target.

I'm having a look now to see how hard this would be to implement.

**Comment by l0ss** [comment]
OK I think it was actually super easy and I think i've got it working in ACLCrimes branch.

I've only implemented one relay rule using the new functionality, but tl;dr .ps1 files should fork and match on both the 'cmd.exe' content rules and the ps1-specific ones.

Please have a look at the changes and let me know what you think and whether it'll work for what you're trying to do. I think this might actually open up some opportunities for extra efficiency, especially around the certificate parsing stuff.

**Comment by hkelley** [comment]
Looks good after a few test runs.   I'm not seeing the matched string/text,  but that might be a setup error on my part  Will double check that.

Overall, I am getting the differentiation I hoped for.  Thank you.

Config:
```

# This relay hooks the next rules via RelayTargets
[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "ConfigContentByExt"
MatchAction = "Relay"
RelayTargets = ["KeepSqlStringYellow","KeepSqlStringRed"]
Description = "Files with these extensions will be subjected to a generic search for keys and such."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = [ ".json", ".config"]
Triage = "Green"

[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepSqlStringYellow"
MatchAction = "Snaffle"
Description = "Match SQL connection strings that appear to use integrated security (so no passwords)."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = ["Data Source=.+Integrated Security=true"]
Triage = "Yellow"

[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepSqlStringRed"
MatchAction = "Snaffle"
Description = "Match SQL connection strings that appear to have a password."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = ["Data Source=.+Password=.+"]
Triage = "Red"
```

Result Examples:

```
[me@here]2021-10-30 10:29:06Z[File]YellowKeepSqlStringYellowRWMData Source=.+Integrated Security=true9322019-12-31 1:53:15 PM\\server\share\sub\appsettings.Dev.json
[me@here]2021-10-30 10:29:06Z[File]RedKeepSqlStringRedRWMData Source=.+Password=.+9322019-12-31 1:53:15 PM\\server\share\sub\appsettings.Dev.json

```

**Comment by l0ss** [comment]
reckon you can submit a PR with this?

**Comment by hkelley** [comment]
Yes, I should be able to.  I'm a github novice so I'll wait until the #69 PR is complete and then fork from there.

**Comment by l0ss** [comment]
fixed in #69

**Comment by hkelley** [comment]
Given the way snaffler does queueing and threading,  I'm guessing this is a long shot,  but can you think of a way to have RelayTargets work like a case statement and break out after a match?

**Comment by l0ss** [comment]
I'm not sure I follow what you're asking - are you on the BloodHound slack by any chance? Chat might be easier on there?
