### ISSUE TITLE
Execute Snaffler from Non-Domain Joined Computer

### ISSUE THREAD

**Issue by CT-H00K** [SnaffCon/Snaffler#75]
Hi, 
I recently tried snaffler, but I used it on a non-domain joined computer where I was logged-in using an azure account. I had a VPN connection, so DC was reachable. However it was not working properly. I tried executing it via a runas /netonly command prompt but still not working. I did not find any parameter like --ldapusername --ldappassword. 

Will there be support in the future to be able to provide a custom domain / credentials to execute snaffler from a non-domain joined computer?

**Comment by l0ss** [comment]
runas /netonly should work if you pass it a domain controller's IP with `-c` and the domain name with `-d`. Please let me know if it works.

If it still doesn't work please run with `-v debug` and share as much error message content as you can.

**Comment by l0ss** [comment]
closed pending further information.
