### ISSUE TITLE
Negative searching for exact file name/folder matches

### ISSUE THREAD

**Issue by infosecconsultant** [SnaffCon/Snaffler#85]
Hello again!
So my scenario currently is this: 
After logging in to a couple of boxes, I realise that whle they are all _supposed_ to have 'Generic EDR', a few hosts do not. 

There's a few ways to go about generating a list of hosts that do not have 'Generic EDR' installed, but the easiest way to check would be to simply look for the presence of the folder/files located at `C:\program files\GenericEDR\` or `C:\program files\GenericEDR\genericedr.exe. `

What I'd like to be able to do is generate a list of hosts using snaffler that do not have this folder or file present and then I can target those specifically for further testing. In this use case, no other files or folders would need to be searched for or reported on (ie, the usual file searches need not apply). If a full path is specified `C:\program files\GenericEDR\` then it only needs to check for the presence/abscence of that specific path. If only a file name is specified like `genericedr.exe` then the whole system can be scanned for it and the full path it was found in can be listed as well. 

Would this be something that could be added? 

Many thanks!

**Comment by l0ss** [comment]
The short answer is that Snaffler is not the right tool for this - I'd suggest using PowerShell to put together a list of domain computers, then iterate over the machines in the list doing something like `get-child item "\\$hostname\c$\Program Files\GenericEDR"`, catching the errors for hosts that don't have the directory.

**Comment by l0ss** [comment]
of course I mean `get-childitem`, not `get-child item`
