### ISSUE TITLE
Discard Rules not obeyed

### ISSUE THREAD

**Issue by cmprmsd** [SnaffCon/Snaffler#88]
The new rule folders and toml files are nice. I wonder though how the order is determined.
I tested the branch and noticed that `PathRules\Discard\DiscardWinSystemDirs.toml` is ignored e.g.
Maybe it matches but not early enough. Is there logic that does check all discard rules before the keeper rules?
At least this happens here with a patched (go get it compile) UltraSnaffler version.

![image](https://user-images.githubusercontent.com/73472903/155842478-3f0822f9-7bc5-432f-a6e6-ecf68f59e6a8.png)

I see at least this which should make it to be the correct order:
```csharp
public enum MatchAction
    {
        Discard,
        SendToNextScope,
        Snaffle,
        Relay,
        CheckForKeys,
        EnterArchive
    }
```
Same issue on Snaffler without Ultra.

_Originally posted by @cmprmsd in https://github.com/SnaffCon/Snaffler/issues/78#issuecomment-1052086259_

I'm looking into it a bit and it seems the dirResult object is correctly set to ScanDir = false.
But the snaffling part does ignore it:

I added the following to ClassifyDir:
```csharp
case MatchAction.Discard:
                        dirResult.ScanDir = false;
                        Mq.Info("Scan: " + dirResult.ScanDir.ToString() + " "+ dirResult.DirPath.ToString());
                        return dirResult;
```

The output shows that the directory is still being searched:
```
2022-02-26 12:42:55Z	[Info]	Scan: False C:\Windows\System32\de-DE
[File]	Green	KeepNameContainsGreen	R			passw	3584	2019-12-07 14:51:01Z	C:\Windows\System32\de-DE\PasswordOnWakeSettingFlyout.exe.mui	PasswordOnWakeSettingFlyout.exe.mui
[File]	Green	KeepNameContainsGreen	R			passw	4608	2019-12-07 14:50:59Z	C:\Windows\System32\de-DE\PasswordEnrollmentManager.dll.mui	PasswordEnrollmentManager.dll.mui
```

I also added some debugging to WalkTree and there seems to be a double calling on the function:
```
02-26 14:30:19Z	[Info]	Scan in WalkTree: True C:\Windows\System32\de-DE\Licenses
02-26 14:30:31Z	[Info]	Scan: False C:\Windows\System32\de-DE\Licenses
02-26 14:30:31Z	[Info]	Scan in WalkTree: False C:\Windows\System32\de-DE\Licenses
```

**Comment by l0ss** [comment]
Sounds like this might be an interesting bug that was present before but the change to rules has flushed it out. I'll take a look, thanks!

**Comment by l0ss** [comment]
I think I've fixed this in the newrules branch, please test and let me know if the issue is still there. There were actually two separate issues you've flushed out here:

1) we weren't sorting rules to put discard rules first. the old rules architecture bypassed this issue by adding the discard rules to their respective lists before other rules.
2) there was a logic bug where an extra treewalker job would be kicked off for every 'path' rule - this means that every dir was getting scanned twice.

Great job spotting this issue, this should result in a substantial performance improvement!

**Comment by cmprmsd** [comment]
Very cool. Thank you for explaining the causes :) 

I think the share discovery still has some double scan or highlight behavior as the notification about important shares is shown twice:
![image](https://user-images.githubusercontent.com/73472903/156597205-6df9b1b6-1cc2-40a3-8ffc-914a349bb4c0.png)

One time as `Green` and the other time as `Black`

**Comment by l0ss** [comment]
The good news is it's not actually scanning those shares twice, it's just raising two separate 'share findings' - one for 'a share was found that we could list' (the green one) and one for 'a C$ or admin$ was found that we could list' (the black one).

This is essentially functioning as intended, it's just not as clear as it could be.
