### ISSUE TITLE
Share Lister Functionality

### ISSUE THREAD

**Issue by cmprmsd** [SnaffCon/Snaffler#89]
I think there is an issue with the `-a` flag, which only runs the Sharefinder and shows the identified shares.
At least for me on the test domain the tool does not output many if any shares when I pass the flag.

Running the full scan does show many more shares.

If you need examples, just ask :)

**Comment by l0ss** [comment]
Examples would definitely help - especially if you can figure out any patterns to it.

**Comment by cmprmsd** [comment]
Okay, I turned on degub and it shows many shares as debug messages. However, only my own shares on the local machine are identified as `[Share]`. 

`.\ultraSnaffler.exe -y -a -s -v degub`
```tsv
...
[Degub] Share discovered: \\myhost\ADMIN$
[Share] Black   \\myhost\ADMIN$
[Degub] Share discovered: \\myhost\C$
[Share] Black   \\myhost\C$
...
[Degub] Share discovered: \\anotherHost\NETLOGON
[Degub] Share discovered: \\anotherHost\SYSVOL
[Degub] Share discovered: \\anotherHost\C$
[Degub] Share discovered: \\anotherHost\D$
...
```

To some of the debug-only listed shares, I have access (sysvol) to others I don't (C$ on the dc). I assume Snaffler tries to verify read access and this does fail on any host but my own. 

Not sure why though.

Also this does not explain yet, why it works on scans without the parameter `-a` maybe the TreeWalkers are started in any case.

```
[Degub] Share discovered: \\host\NETLOGON
[Degub] Share discovered: \\host\print$
[Degub] Share discovered: \\host\SYSVOL
[Degub] Share discovered: \\host\IPC$
[Degub] Share discovered: \\host\print$
[Share] Green   \\host\SYSVOL R
[Share] Green   \\host\NETLOGON       R
```

The R's are missing on the `-a` scan. Maybe it's not verified at all and you (as developer) can now decide to 
* switch the debug information to `[Share]` when using `-a` 
or
* make it consistent and check at least the share privileges. 

I still don't know why the local shares of the scanning host itself show up though. :smile:

**Comment by l0ss** [comment]
nah there was a legit bug, i've fixed it in newrules branch now, thanks for that.

the local shares show up because the local machine is a domain member computer and has shares 🤷‍♂️ I could write some code to explicitly exclude it but not sure what benefit that would provide.

**Comment by cmprmsd** [comment]
Fix confirmed! Thanks :)
